
package com.oops.atm_with_gui;

import java.sql.*;
import javax.swing.*;
/**
 *
 * @author athar
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SUAddressIN = new javax.swing.JTextArea();
        SUAccNoIN = new javax.swing.JTextField();
        SULastNameIN = new javax.swing.JTextField();
        SUFirstNameIN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SUPinIN = new javax.swing.JTextField();
        SUOccupationIN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SUPhoneIN = new javax.swing.JTextField();
        SUEducationIN = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        SUSubmitBtn = new javax.swing.JButton();
        SULoginBtn = new javax.swing.JButton();
        SUDobIN = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(6, 40, 61));

        jPanel2.setBackground(new java.awt.Color(19, 99, 223));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 40, 61));
        jLabel1.setText("ATM");

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setText("Choose Service");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(223, 246, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 99, 223));
        jLabel3.setText("Account No:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 99, 223));
        jLabel4.setText("SignUp");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(19, 99, 223));
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 99, 223));
        jLabel6.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 99, 223));
        jLabel7.setText("Address:");

        SUAddressIN.setBackground(new java.awt.Color(71, 181, 255));
        SUAddressIN.setColumns(20);
        SUAddressIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUAddressIN.setForeground(new java.awt.Color(6, 40, 61));
        SUAddressIN.setRows(5);
        jScrollPane1.setViewportView(SUAddressIN);

        SUAccNoIN.setBackground(new java.awt.Color(71, 181, 255));
        SUAccNoIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUAccNoIN.setForeground(new java.awt.Color(6, 40, 61));
        SUAccNoIN.setText("jTextField1");
        SUAccNoIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUAccNoINActionPerformed(evt);
            }
        });

        SULastNameIN.setBackground(new java.awt.Color(71, 181, 255));
        SULastNameIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SULastNameIN.setForeground(new java.awt.Color(6, 40, 61));
        SULastNameIN.setText("jTextField1");
        SULastNameIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SULastNameINActionPerformed(evt);
            }
        });

        SUFirstNameIN.setBackground(new java.awt.Color(71, 181, 255));
        SUFirstNameIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUFirstNameIN.setForeground(new java.awt.Color(6, 40, 61));
        SUFirstNameIN.setText("jTextField1");
        SUFirstNameIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUFirstNameINActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 99, 223));
        jLabel8.setText("PIN:");

        SUPinIN.setBackground(new java.awt.Color(71, 181, 255));
        SUPinIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUPinIN.setForeground(new java.awt.Color(6, 40, 61));
        SUPinIN.setText("jTextField1");
        SUPinIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPinINActionPerformed(evt);
            }
        });

        SUOccupationIN.setBackground(new java.awt.Color(71, 181, 255));
        SUOccupationIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUOccupationIN.setForeground(new java.awt.Color(6, 40, 61));
        SUOccupationIN.setText("jTextField1");
        SUOccupationIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUOccupationINActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(19, 99, 223));
        jLabel9.setText("Occupation:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(19, 99, 223));
        jLabel10.setText("Education:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 99, 223));
        jLabel11.setText("Phone:");

        SUPhoneIN.setBackground(new java.awt.Color(71, 181, 255));
        SUPhoneIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUPhoneIN.setForeground(new java.awt.Color(6, 40, 61));
        SUPhoneIN.setText("jTextField1");
        SUPhoneIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPhoneINActionPerformed(evt);
            }
        });

        SUEducationIN.setBackground(new java.awt.Color(71, 181, 255));
        SUEducationIN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SUEducationIN.setForeground(new java.awt.Color(6, 40, 61));
        SUEducationIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uneducated", "School", "UG", "PG", "PHD", "Self Employed" }));
        SUEducationIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUEducationINActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 99, 223));
        jLabel12.setText("DOB:");

        SUSubmitBtn.setBackground(new java.awt.Color(71, 181, 255));
        SUSubmitBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SUSubmitBtn.setForeground(new java.awt.Color(19, 99, 223));
        SUSubmitBtn.setText("Submit");
        SUSubmitBtn.setName("DepositBtn"); // NOI18N
        SUSubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUSubmitBtnMouseClicked(evt);
            }
        });
        SUSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUSubmitBtnActionPerformed(evt);
            }
        });

        SULoginBtn.setBackground(new java.awt.Color(71, 181, 255));
        SULoginBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SULoginBtn.setForeground(new java.awt.Color(19, 99, 223));
        SULoginBtn.setText("Login");
        SULoginBtn.setName("DepositBtn"); // NOI18N
        SULoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SULoginBtnActionPerformed(evt);
            }
        });

        SUDobIN.setBackground(new java.awt.Color(71, 181, 255));
        SUDobIN.setForeground(new java.awt.Color(6, 40, 61));
        SUDobIN.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(SUAccNoIN)
                    .addComponent(SULastNameIN)
                    .addComponent(SUFirstNameIN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SUPhoneIN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SUOccupationIN)
                            .addComponent(SUPinIN)
                            .addComponent(SUEducationIN, 0, 276, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SUSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SULoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUDobIN, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUAccNoIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUFirstNameIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SULastNameIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUPinIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUEducationIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUOccupationIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SUPhoneIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(SUDobIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(SUSubmitBtn)))
                .addGap(18, 18, 18)
                .addComponent(SULoginBtn)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUAccNoINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUAccNoINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUAccNoINActionPerformed

    private void SULastNameINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SULastNameINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SULastNameINActionPerformed

    private void SUFirstNameINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUFirstNameINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUFirstNameINActionPerformed

    private void SUPinINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPinINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUPinINActionPerformed

    private void SUOccupationINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUOccupationINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUOccupationINActionPerformed

    private void SUPhoneINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPhoneINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUPhoneINActionPerformed

    private void SUEducationINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUEducationINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUEducationINActionPerformed

    private void SUSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUSubmitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUSubmitBtnActionPerformed

    private void SULoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SULoginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SULoginBtnActionPerformed
    Connection con = null;
    PreparedStatement pst = null ;
    ResultSet Rs = null ;
    Statement St = null ;

    private void clear(){
        SUAccNoIN.setText("");
        SUFirstNameIN.setText("");
        SULastNameIN.setText("");
        SUDobIN.setDate(null);
        SUPinIN.setText("");
        SUAddressIN.setText("");
        SUEducationIN.setSelectedIndex(-1);
        SUOccupationIN.setText("");
        SUPhoneIN.setText("");
    }
    private void SUSubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUSubmitBtnMouseClicked
        if(SUAccNoIN.getText().isEmpty() || SUFirstNameIN.getText().isEmpty() || SULastNameIN.getText().isEmpty() || SUAddressIN.getText().isEmpty() || SUPinIN.getText().isEmpty() || SUOccupationIN.getText().isEmpty() || SUPhoneIN.getText().isEmpty() || SUPinIN.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter all details");
        }
        else{
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, e);
            }
            try{

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb", "root", "");
                PreparedStatement Add = con.prepareStatement("INSERT INTO accounttbl VALUES(?,?,?,?,?,?,?,?,?,?);");
                Add.setInt(1,Integer.parseInt(SUAccNoIN.getText()));
                Add.setString(2,SUFirstNameIN.getText());
                Add.setString(3,SULastNameIN.getText());
                Add.setString(4, String.valueOf(SUDobIN.getDate()));
                Add.setString(5,SUPhoneIN.getText());
                Add.setString(6,SUAddressIN.getText());
                Add.setString(7,SUEducationIN.getSelectedItem().toString());
                Add.setString(8,SUOccupationIN.getText());
                Add.setInt(9,0);
                Add.setInt(10,Integer.parseInt(SUPinIN.getText()));
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog ( this , " Account Saved " ) ;
                con.close();
                clear();



                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,e);
            }

        }
    }//GEN-LAST:event_SUSubmitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SUAccNoIN;
    private javax.swing.JTextArea SUAddressIN;
    private com.toedter.calendar.JDateChooser SUDobIN;
    private javax.swing.JComboBox<String> SUEducationIN;
    private javax.swing.JTextField SUFirstNameIN;
    private javax.swing.JTextField SULastNameIN;
    private javax.swing.JButton SULoginBtn;
    private javax.swing.JTextField SUOccupationIN;
    private javax.swing.JTextField SUPhoneIN;
    private javax.swing.JTextField SUPinIN;
    private javax.swing.JButton SUSubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
